"""
Evidence Contract — the internal API between all pipeline modules.

Every module downstream of ingestion reads and writes this object.
`laya` stays populated with sane defaults/nulls even when Laya (P1)
isn't wired up yet, so fusion never has to special-case its absence.

This is the CONTRACT, not just a data shape.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


# ─── Enums ───

class RiskLevel(str, Enum):
    """Risk levels — used identically across every screen."""
    UNKNOWN = "UNKNOWN"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class InputType(str, Enum):
    """Supported input types."""
    TEXT = "text"
    URL = "url"
    SMS = "sms"
    EMAIL = "email"
    CHAT = "chat"
    SCREENSHOT = "screenshot"


class UserState(str, Enum):
    """Adaptive response state machine states."""
    RECEIVED = "received"
    CLICKED = "clicked"
    ENTERED_CREDENTIALS = "entered_credentials"
    PAID = "paid"


class EvidenceType(str, Enum):
    """Types of evidence items — each renders as its own labeled item in the UI."""
    RULE_MATCH = "rule_match"
    URL_ANALYSIS = "url_analysis"
    BRAND_MISMATCH = "brand_mismatch"
    THREAT_INTEL_HIT = "threat_intel_hit"
    THREAT_INTEL_MISS = "threat_intel_miss"
    LAYA_SIGNAL = "laya_signal"
    IOC_EXTRACTED = "ioc_extracted"
    PATTERN_MATCH = "pattern_match"
    DOMAIN_AGE = "domain_age"
    REDIRECT_CHAIN = "redirect_chain"
    CAMPAIGN_LINK = "campaign_link"


# ─── Sub-models ───

class URLSignal(BaseModel):
    """Signals extracted from a single URL."""
    url: str
    domain: str
    signals: list[str] = Field(default_factory=list)
    is_shortened: bool = False
    redirect_chain: list[str] = Field(default_factory=list)
    final_url: Optional[str] = None


class BrandMatch(BaseModel):
    """Brand impersonation detection result."""
    brand_name: str
    confidence: float = Field(ge=0.0, le=1.0)
    match_type: str = ""  # "exact", "similarity", "domain_mismatch"
    legitimate_domain: Optional[str] = None


class LayaResult(BaseModel):
    """
    Laya typed-decision output. Populated with nulls/defaults when Laya
    is not active — fusion reads this without special-casing.
    """
    fraud: Optional[float] = None
    brand_impersonation: Optional[float] = None
    credential_request: Optional[float] = None
    deep_analysis_required: Optional[float] = None
    available: bool = False  # False when Laya is not wired up


class ThreatIntelResult(BaseModel):
    """Single threat-intelligence source result."""
    source: str  # P0: "safe_browsing", "phishtank" | P2: "urlhaus", "abuseipdb"
    match: Optional[bool] = None  # None = lookup failed / unavailable
    details: Optional[str] = None
    lookup_url: Optional[str] = None
    error: Optional[str] = None  # Non-null when API call failed
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class RiskAssessment(BaseModel):
    """Fused risk assessment."""
    level: RiskLevel = RiskLevel.UNKNOWN
    score: float = Field(default=0.0, ge=0.0, le=1.0)
    calibrated: bool = False
    contributing_factors: list[str] = Field(default_factory=list)


class EvidenceItem(BaseModel):
    """
    Single piece of evidence — rendered as its own labeled item in the UI
    with a source. Never collapsed into one opaque verdict.
    """
    type: EvidenceType
    source: str  # Which module produced this evidence
    description: str
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    raw_data: Optional[dict] = None  # Preserved for provenance


class GeminiExplanation(BaseModel):
    """
    Explanation output — structured, never freeform.
    Can be produced by Gemini or deterministic template fallback.
    """
    summary: str = ""
    reasons: list[str] = Field(default_factory=list)
    attack_path: list[str] = Field(default_factory=list)
    user_action: list[str] = Field(default_factory=list)
    uncertainty: str = ""
    model_used: str = ""  # "gemini-2.0-flash-lite", "deterministic-fallback", etc.
    evidence_cited: list[str] = Field(default_factory=list)  # IDs of evidence items used
    is_fallback: bool = False  # True when generated by deterministic template


class AdaptiveResponse(BaseModel):
    """State-dependent guidance based on user's interaction level."""
    user_state: UserState = UserState.RECEIVED
    immediate_actions: list[str] = Field(default_factory=list)
    recovery_steps: list[str] = Field(default_factory=list)
    reporting_info: list[str] = Field(default_factory=list)
    urgency: str = "normal"  # "normal", "urgent", "critical"


class FraudDNA(BaseModel):
    """Fraud DNA fingerprint for campaign correlation (P2)."""
    fingerprint: Optional[str] = None
    campaign_id: Optional[str] = None
    related_incidents: list[str] = Field(default_factory=list)
    available: bool = False  # False until Fraud DNA module is wired up


# ─── Main Evidence Contract ───

class IncidentEvidence(BaseModel):
    """
    THE Evidence Contract.

    Every module downstream of ingestion reads and writes this object.
    All fields have sane defaults so the pipeline works regardless of
    which optional modules are active.

    Invariants:
    - `incident_id` is set once at creation, never changed.
    - `laya` is always present (with `available=False` when Laya isn't wired).
    - `fraud_dna` is always present (with `available=False` when DNA isn't wired).
    - `evidence` is append-only — modules add items, never remove them.
    - `threat_intel` entries include `error` when a lookup failed.
    """
    # Identity
    incident_id: str = Field(default_factory=lambda: f"INC-{datetime.now(timezone.utc).strftime('%Y')}-{uuid.uuid4().hex[:8].upper()}")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    # Input
    input_type: InputType = InputType.TEXT
    language: str = "en"
    message: str = ""
    original_input: Optional[str] = None  # Preserved before normalization

    # Extraction
    urls: list[URLSignal] = Field(default_factory=list)
    brands: list[BrandMatch] = Field(default_factory=list)
    iocs: list[str] = Field(default_factory=list)  # Indicators of compromise

    # Analysis
    laya: LayaResult = Field(default_factory=LayaResult)
    threat_intel: list[ThreatIntelResult] = Field(default_factory=list)
    rule_matches: list[str] = Field(default_factory=list)
    fraud_category: Optional[str] = None  # "banking", "courier", "government", "lottery", etc.

    # Fusion
    risk: RiskAssessment = Field(default_factory=RiskAssessment)
    evidence: list[EvidenceItem] = Field(default_factory=list)

    # Explanation
    explanation: Optional[GeminiExplanation] = None

    # Response
    response: Optional[AdaptiveResponse] = None

    # Campaign (P2)
    fraud_dna: FraudDNA = Field(default_factory=FraudDNA)

    # Processing metadata
    processing_time_ms: Optional[float] = None
    modules_executed: list[str] = Field(default_factory=list)
    modules_failed: list[str] = Field(default_factory=list)
    errors: list[str] = Field(default_factory=list)
